# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chen-Yu Liu 劉宸銉
email: d10245003@g.ntu.edu.tw
description: >- # this means to ignore newlines until "baseurl:"
  
twitter_username: username
github_username: username
minimal_mistakes_skin: dirt #contrast #mint
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 7 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Chen-Yu Liu"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Currently a Ph.D. candidate at the Graduate Institute of Applied Physics, National Taiwan University, and a research intern at Hon Hai Quantum Computing Research Center. "
  links:
    - label: "Google Scholar"
      icon: "fab fa-google"
      url: "https://scholar.google.com/citations?user=tp83gZMAAAAJ&hl=zh-TW&fbclid=IwAR05JyNRCINgYgaSrpXD4VeU523qT8T7d0bI3onrT7DM-GkXv193mFnI95s"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CYLphysics"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/chen-yu-liu-549289194/"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Google Scholar"
      icon: "fab fa-google"
      url: "https://scholar.google.com/citations?user=tp83gZMAAAAJ&hl=zh-TW&fbclid=IwAR05JyNRCINgYgaSrpXD4VeU523qT8T7d0bI3onrT7DM-GkXv193mFnI95s"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/chen-yu-liu-549289194/"
header:
  image: /assets/images/header1.jpg
  

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
